CREATE TABLE Languages(
	ID INTEGER IDENTITY(1,1),
	Culture VARCHAR(6) NOT NULL,
	Name VARCHAR(60) NOT NULL,

	PRIMARY KEY(ID)
);

CREATE TABLE StringResources(
	ID INTEGER IDENTITY(1,1),
	Language_ID INTEGER NOT NULL,
	Name VARCHAR(80) NOT NULL,
	Value TEXT DEFAULT 'N/A',

	PRIMARY KEY(ID),
	FOREIGN KEY(Language_ID) REFERENCES Languages(ID)
);



CREATE TABLE Planet(
	ID INTEGER IDENTITY(1,1),
	Name VARCHAR(70) NOT NULL,
	ImagePath VARCHAR(MAX),

	PRIMARY KEY(ID)
);

CREATE TABLE Planet_StringResources(
	ID INTEGER IDENTITY(1,1) NOT NULL,
	Name VARCHAR(70) NOT NULL DEFAULT 'N/A',
	ShortDescription VARCHAR(MAX),
	StateOfMatter VARCHAR(30),
	
	PRIMARY KEY(ID)
);

CREATE TABLE Languages_Planet(
	Language_ID INTEGER NOT NULL,
	Planet_ID INTEGER NOT NULL,
	PSR_ID INTEGER UNIQUE,

	PRIMARY KEY(Language_ID, Planet_ID),
	FOREIGN KEY(Language_ID) REFERENCES Languages(ID),
	FOREIGN KEY(Planet_ID) REFERENCES Planet(ID),
	FOREIGN KEY(PSR_ID) REFERENCES Planet_StringResources(ID)
);

CREATE TABLE Planet_Info(
	Planet_ID INTEGER NOT NULL,
	LengthFromSun DECIMAL DEFAULT 0,
	ShortDescription VARCHAR(MAX) DEFAULT 'N/A',
	StateOfMatter VARCHAR(30) DEFAULT 'N/A',
	Diameter FLOAT DEFAULT 0,
	TravelTimeAroundSun FLOAT DEFAULT 0,
	Temperature DECIMAL DEFAULT 0,
	AtmosphericPressure DECIMAL DEFAULT null,
	NumberOfMoons INTEGER DEFAULT 0,

	PRIMARY KEY(Planet_ID),
	FOREIGN KEY(Planet_ID) REFERENCES Planet(ID)
);